### ISSUE TITLE
[Bug]: Rule Item Form Maximum call stack size exceeded

### ISSUE THREAD

**Issue by HubertChen1** [janechu/design-to-code#221]
### What happened?

For rule schemas, the rule items cannot be viewed in a form when selected. EX. ICE
![Screenshot 2024-02-21 at 12 05 39 PM](https://github.com/janechu/design-to-code/assets/160767821/bf047416-6584-49dd-802a-3132ab493ed2)

### Relevant log output

```shell
Unexpected Application Error!
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132158)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
    at $r (https://ccs-claims-dv1.geico.net/vendors.js:8:132242)
```

**Comment by Reneechen108** [comment]
Here is the schema
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://example.com/1794-example.schema.json",
  "title": "Predicate Engine",
  "type": "object",
  "required": ["listNode", "defaultValue"],
  "properties": {
    "listNode": {
      "title": "Rule Set",
      "$ref": "#/$defs/ListNode"
    },
    "defaultValue": {
      "title": "Default Value",
      "type": "string"
    }
  },
  "$defs": {
    "Node": {
      "title": "Node",
      "type": "object",
      "properties": {
        "exactStringMatchNode": {
          "$ref": "#/$defs/ExactStringMatchNode"
        },
        "terminalNode": {
          "$ref": "#/$defs/TerminalNode"
        }
      }
    },
    "ListNode": {
      "title": "List Node",
      "type": "array",
      "items": {
        "title": "Node",
        "$ref": "#/$defs/Node"
      }
    },
    "ExactStringMatchNode": {
      "title": "String Match Node",
      "type": "object",
      "required": ["factKey", "targetValue"],
      "properties": {
        "factKey": {
          "title": "Input Field",
          "type": "string"
        },
        "targetValue": {
          "title": "Match Value",
          "type": "string"
        },
        "next": {
          "title": "Next",
          "$ref": "#/$defs/Node"
        }
      }
    },
    "TerminalNode": {
      "title": "List Node",
      "type": "object",
      "required": ["result"],
      "properties": {
        "result": {
          "title": "Result",
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by janechu** [comment]
Thanks @Reneechen108, investigating.
